import { expectType } from '../../expect-type.mjs';
import { range as rangeIterator } from '../../iterator/index.mjs';

export const zeros = <N extends SizeType.ArgArr>(
  len: N,
): N extends SmallUint
  ? ArrayOfLength<N, 0>
  : N extends SizeType.ArgArrPositive
    ? NonEmptyArray<0>
    : readonly 0[] =>
  // eslint-disable-next-line total-functions/no-unsafe-type-assertion
  Array.from<0>({ length: len }).fill(0) as never;

export const seq = <N extends SizeType.ArgArr>(
  len: N,
): N extends SmallUint
  ? Seq<N>
  : N extends SizeType.ArgArrPositive
    ? NonEmptyArray<SizeType.Arr>
    : readonly SizeType.Arr[] =>
  // eslint-disable-next-line total-functions/no-unsafe-type-assertion
  Array.from({ length: len }, (_, i) => i) as never;

export const create = <const V, N extends SizeType.ArgArr>(
  len: N,
  init: V,
): N extends SmallUint
  ? ArrayOfLength<N, V>
  : N extends SizeType.ArgArrPositive
    ? NonEmptyArray<V>
    : readonly V[] =>
  // eslint-disable-next-line total-functions/no-unsafe-type-assertion
  Array.from({ length: Math.max(0, len) }, () => init) as never;

export const newArray = create;

export const generate = <T,>(
  generatorFn: () => Generator<T, void, unknown>,
): readonly T[] => Array.from(generatorFn());

export const generateAsync = <T,>(
  generatorFn: () => AsyncGenerator<T, void, unknown>,
): Promise<readonly T[]> => Array.fromAsync(generatorFn());

export const copy = <const Ar extends readonly unknown[]>(array: Ar): Ar =>
  // eslint-disable-next-line total-functions/no-unsafe-type-assertion
  array.slice() as unknown as Ar;

/**
 * @internal
 * Helper type for `range` function to represent a sequence of numbers up to N-1.
 * `LEQ[N]` would be `0 | 1 | ... | N-1`.
 */
type LT = Readonly<{
  [N in SmallUint]: Index<N>;
}>;

/**
 * @template S The start of the range (inclusive), constrained to `SmallUint`.
 * @template E The end of the range (exclusive), constrained to `SmallUint`.
 * @internal
 * This type is used to avoid incorrect type calculation results for unions with `Seq`.
 * It computes the type of an array generated by `Arr.range(S, E)`.
 * If `S` or `E` is a union type, it falls back to a more general `readonly number[]` type
 * to prevent overly complex or incorrect tuple/union types.
 * Otherwise, it computes a precise tuple type like `readonly [S, S+1, ..., E-1]`.
 */
type RangeList<S extends SmallUint, E extends SmallUint> =
  BoolOr<IsUnion<S>, IsUnion<E>> extends true
    ? readonly RelaxedExclude<LT[E], LT[Min<S>]>[] // Avoid incorrect type calculation for unions with Seq
    : List.Skip<S, Seq<E>>;

expectType<RangeList<1, 5>, readonly [1, 2, 3, 4]>('=');
expectType<RangeList<1, 2>, readonly [1]>('=');
expectType<RangeList<1, 1>, readonly []>('=');
expectType<RangeList<1, 1 | 3>, readonly (1 | 2)[]>('=');
expectType<RangeList<1 | 3, 3 | 5>, readonly (1 | 2 | 3 | 4)[]>('=');
expectType<RangeList<1 | 2 | 3, 5 | 6 | 7>, readonly (1 | 2 | 3 | 4 | 5 | 6)[]>(
  '=',
);
expectType<RangeList<5, 1>, readonly []>('=');

/**
 * Creates an array of numbers within a specified range with optional step
 * increment.
 *
 * This function generates arithmetic sequences with advanced compile-time
 * type inference:
 *
 * - When `start` and `end` are {@link SmallUint} literals and `step` is 1 (or
 *   omitted), returns a precise tuple type
 * - When parameters are runtime values, returns appropriate array types based
 *   on sign constraints
 * - Empty arrays are returned for invalid ranges (e.g., start ≥ end with
 *   positive step)
 * - Never throws exceptions - invalid parameters result in empty arrays
 *
 * **SmallUint Constraint:** The {@link SmallUint} constraint (0-255) enables
 * precise tuple type inference for compile-time known ranges. This allows
 * TypeScript to compute exact tuple types like `readonly [1, 2, 3, 4]`
 * instead of generic `readonly number[]`.
 *
 * **Type Inference Behavior:**
 *
 * - Literal {@link SmallUint} values with step=1 → precise tuple type
 *   (`RangeList<S, E>`)
 * - Non-negative parameters → `readonly SafeUint[]`
 * - Mixed signs or negative parameters → `readonly SafeInt[]`
 * - Runtime values → lose precise typing but maintain safety
 *
 * @example
 *
 * ```ts
 * const ascending = Arr.range(asUint32(1), asUint32(5));
 * const empty = Arr.range(asUint32(2), asUint32(2));
 *
 * assert.deepStrictEqual(ascending, [1, 2, 3, 4]);
 * assert.deepStrictEqual(empty, []);
 * ```
 *
 * @template S The type of the start value. When a {@link SmallUint} literal
 *   (0-255), enables precise tuple typing.
 * @template E The type of the end value. When a {@link SmallUint} literal
 *   (0-255), enables precise tuple typing.
 * @param start The start of the range (inclusive). Must be a safe integer.
 *   Supports:
 *
 *   - **Literal {@link SmallUint}:** Enables precise tuple types (0-255)
 *   - **Runtime {@link SafeInt}:** Fallback to general array types
 *   - **Negative values:** Supported for countdown sequences
 *
 * @param end The end of the range (exclusive). Must be a safe integer.
 *   Supports:
 *
 *   - **Literal {@link SmallUint}:** Enables precise tuple types (0-255)
 *   - **Runtime {@link SafeInt}:** Fallback to general array types
 *   - **Equal to start:** Results in empty array
 *
 * @param step The step increment (default: 1). Must be a non-zero safe
 *   integer.
 *
 *   - **Positive step:** generates increasing sequence from start to end
 *   - **Negative step:** generates decreasing sequence from start to end
 *   - **Zero step:** Not allowed (branded type prevents this)
 *
 * @returns An immutable array containing the arithmetic sequence. Return type
 *   depends on parameters:
 *
 *   - `RangeList<S, E>` (precise tuple like `readonly [1, 2, 3, 4]`) when `S` and
 *       `E` are {@link SmallUint} literals and step is 1
 *   - `readonly SafeUint[]` when all parameters are non-negative
 *   - `readonly SafeInt[]` for general integer ranges including negative values
 *
 * @throws Never throws - invalid ranges simply return empty arrays
 * @see {@link seq} for creating sequences starting from 0
 * @see {@link SmallUint} for understanding the constraint that enables precise typing
 * @see {@link SafeInt} and {@link SafeUint} for the safe integer types used
 */
export function range<S extends SmallUint, E extends SmallUint>(
  start: S,
  end: E,
  step?: 1,
): RangeList<S, E>;

export function range(
  start: SafeUintWithSmallInt,
  end: SafeUintWithSmallInt,
  step?: PositiveSafeIntWithSmallInt,
): readonly SafeUint[];

export function range(
  start: SafeIntWithSmallInt,
  end: SafeIntWithSmallInt,
  step?: NonZeroSafeIntWithSmallInt,
): readonly SafeInt[];

export function range(
  start: SafeIntWithSmallInt,
  end: SafeIntWithSmallInt,
  step: NonZeroSafeIntWithSmallInt = 1,
): readonly SafeInt[] {
  return Array.from(rangeIterator(start, end, step));
}
